### ISSUE TITLE
Data (or download link) file not included 

### ISSUE THREAD

**Issue by wonwon0** [prateekgv/openshoe-sphere_limit#2]
Hi,

I would like to try and reproduce your results in addition to try and incorporate simulated magnetometer data to your implementation.

Would you happen to have a link to make your IMU data available?

Thank you.

**Comment by prateekgv** [comment]
Hi wonwon0,

I used the datasets from publication #9 in the link below. 
http://www.openshoe.org/?page_id=54

I hope that helps.

**Comment by wonwon0** [comment]
thank you for your answer!
